version: '3.8'

services:
  vox-logis-bot:
    build: .
    container_name: vox-logis-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"